use_frameworks!

platform :ios, '9.0'

target 'JLPodLibrary_Example' do
#  pod 'JLPodLibrary'
  pod 'JLPodLibrary', :path => '../'
#  pod 'JLPodLibrary', :podspec => '../JLPodLibrary.podspec'

  target 'JLPodLibrary_Tests' do
    inherit! :search_paths

    
  end
end
